version: '2'
services:
  database: 
    build: database/
    expose:
      - "27017"
    volumes:
      - data-volume:/data/db
    restart: "always"

  database-seed: 
    build: database/seed/
    depends_on:
      - database

  app:
    build: app/
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - CCR_PORT=80
      - CCR_HOST=localhost
      - CCR_MONGO_URL=mongodb://database:27017/ccr
    depends_on:
      - database
    restart: "always"

  reciever:
    build: reciever/
    ports:
      - "5000:5000"
    environment:
      - CCR_SOURCE=tcp://*:5000
      - CCR_MONGO_URL=mongodb://database:27017/ccr
    depends_on:
      - database
    restart: "always"

volumes:
  data-volume:
